version: '3.8'

services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.4-apache
    volumes:
      - **VOLUMEN**:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: my_database
        MYSQL_USER: adri
        MYSQL_PASSWORD: 1234
    ports:
        - "9906:3306"

  ftp:
    image: fauria/vsftpd
    container_name: ftp
    restart: always
    environment:
        FTP_USER: user
        FTP_PASS: pass
    ports:
        - "21:21"
        - "30000-30009:30000-30009"
    volumes:
        - ./ftp:/home/vsftpd/