version: "3.9"
services:
  php:
    build: 
      context: './php/'
      args:
        PHP_VERSION: 7.4
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
    links:
      - mysql
  apache:
    build:
      context: './apache/'
      args:
        APACHE_VERSION: 2.4
    depends_on:
      - php
      - mysql
    links:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "adri"
      MYSQL_PASSWORD: "12345"
    container_name: mysql
  phpmyadmin:
    depends_on:
      - mysql
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: "adri"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - backend
    volumes:
      - /sessions
    container_name: phpmyadmin
networks:
  frontend:
  backend:
volumes:
  data:
